# Permalinks
permalink:           pretty

# Setup
title:               昆仑小站
tagline:             夜月昆仑的知识仓库
url:                 http://yeyuekunlun.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              夜月昆仑
  url:               http://www.jiashiwei.tech
  email:             yeyuekunlun@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/yeyuekunlun/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
